### PR TITLE
BIC estimation improvement

### PR DESCRIPTION
**Pull request by Migelo**
The main part of this pull request is in the updated ipython notebook. The BIC is computed 3 times for each n, where n is the number of lines we try to fit the spectra with. The lowest of the 3 is taken and as soon as the BIC starts increasing with increasing n we take tha n-1 to be our solution and perform a proper fit.

### CODE REVIEW

**Comment by christopherlovell** [comment]
Great, thanks! Have merged all commits but the plot, which I think would be best served and explained within a notebook.

**Comment by christopherlovell** [comment]
As I was about to merge I noticed that the notebooks are pretty large, probably from including all the fitting plots. I could merge and remove the plots, but this will still leave the large versions in the git history. 

Is there any chance you could clean your fork of some of these large files?

**Comment by Migelo** [comment]
I’ll clean them up. And as for the separate plot, I’ll put it in a separate notebook. But I am sailing until 30.9. so after that. :)

Miha

**Comment by Migelo** [comment]
@christopherlovell so you want me to clean the plots and remove them from history, right?

**Pull request closed without merging**
